### ISSUE TITLE
?Portable to leveldb

### ISSUE THREAD

**Issue by heapwolf** [max-mapper/hyperlevel-backup#1]
I haven't really looked under the hood yet, but two thoughts come to mind. 
- If the snapshots are of the complete database this could get quite slow with larger data sets. 
- Leveldb has [`snapshots`](http://leveldb.googlecode.com/git-history/e11bdf1935bc5a46db790ef414110149009f8c6a/doc/index.html) as well. If I'm wrong about the first thought, perhaps its worth looking into opening up the snapshots api so we can experiment more with this kind of replication!

**Comment by max-mapper** [comment]
the leveldb snapshot api is at the key level whereas in hyperleveldb its at the file level, so it would be much slower to use leveldb snapshots for the same thing this repo is doing (full table scans are hellza slow compared to just coping .ldb files)

the way they are implemented in hyperleveldb are really fast because they are at the file level, heres a relevant chat excerpt

06:52 < rescrv> you can also rsync the livebackup and take advantage of its builtin diff algorithm
06:54 < rescrv> you can do this yourself for db copying by omitting any *.sst files that exist on both sids
06:55 < ogd> rescrv: ah, .ssts never change once they are written?
06:55 < rescrv> ogd: correct
06:56 < rescrv> that's why you can backup a 1TB database in literally seconds
06:56 < ogd> this is a nice option... basically if its okay that you bring your database down you can get super fast sync
06:56 < ogd> whereas if you want to keep it available i can offer a networked sync that is slower
06:57 < ogd> (networked meaning serailized data through the leveldb api)
06:59 < rescrv> ogd: the cost of LiveBckup is proportional to a write, plus copying 100KB + write_buffer_size
06:59 < rescrv> By "cost" I mean the time that your DB is unavailable for writes
07:00 < rescrv> the remaining time in that "seconds" number is not going to hold up writes
07:00 < ogd> rescrv: i was thinking in terms of the receiving end in a replication scenario, it could get tricky to merge in remote updates consistently
07:01 < rescrv> ogd: I think if you are doing replication, you can copy the backup and then do a merge with two iterators
07:01 < rescrv> there's other features in HyperLevelDB that make replication cheap, but they require knowing the code well enough that you'd be better looking at the code than asking me
07:02 < rescrv> we use them in HyperDex to take a node offline and copy only the data that it missed in the time it was offline

**Comment by heapwolf** [comment]
Ah super interesting. And `the cost of LiveBckup is proportional to a write`, makes sense.

**Comment by max-mapper** [comment]
though I think rescrv mentioned that he used the snapshot api to build liveBackup (for the consistency part), so maybe that can get upstreamed to google leveldb? not sure how hard that would be

**Comment by rvagg** [comment]
Actually the code to do this is pretty simple, if we can get a good process for doing native plugins for leveldown then this might not be out of the question for vanilla leveldb.

It's unlikely google will pull it in to their leveldb; this is the reason we have these forks.
